[package]
org = "lahirus"
name = "integration_demo"
version = "0.1.0"
distribution = "2201.8.2"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.26"
path = "db/mysql-connector-java-8.0.27.jar"
